version: '3.8'

services:
  plex2jf:
    build: .
    container_name: plex2jf
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config/
      - ./data:/data
    environment:
      - TZ=America/New_York
      - PLEX2JF_LOG_LEVEL=INFO
      - PLEX2JF_DB_PATH=/data/plex2jf.db
